# Profiles Config for Clash Verge

current: RQeqWRX5X3dl
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1783773060
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1783773060
- uid: mgOSqMrfA7GO
  type: merge
  name: null
  file: mgOSqMrfA7GO.yaml
  updated: 1783784988
- uid: sNW5i6kKW7ir
  type: script
  name: null
  file: sNW5i6kKW7ir.js
  updated: 1783784988
- uid: r874XOHEB6Ua
  type: rules
  name: null
  file: r874XOHEB6Ua.yaml
  updated: 1783784988
- uid: pHM19vCad0ht
  type: proxies
  name: null
  file: pHM19vCad0ht.yaml
  updated: 1783784988
- uid: gfnBJU0FgajE
  type: groups
  name: null
  file: gfnBJU0FgajE.yaml
  updated: 1783784988
- uid: LFp2JUCzB0pb
  type: local
  name: 三毛机场临时配置文件-20260606.yaml
  file: LFp2JUCzB0pb.yaml
  desc: ''
  selected:
  - name: GLOBAL
    now: DIRECT
  - name: Proxy
    now: 三毛机场.com
  updated: 1783784988
  option:
    merge: mgOSqMrfA7GO
    script: sNW5i6kKW7ir
    rules: r874XOHEB6Ua
    proxies: pHM19vCad0ht
    groups: gfnBJU0FgajE
- uid: mb8K8IRyb7jZ
  type: merge
  name: null
  file: mb8K8IRyb7jZ.yaml
  updated: 1783789053
- uid: sY3BUB6D8d4i
  type: script
  name: null
  file: sY3BUB6D8d4i.js
  updated: 1783789053
- uid: rrDaWXsjQKS8
  type: rules
  name: null
  file: rrDaWXsjQKS8.yaml
  updated: 1783789053
- uid: pnc8LVDSL8mP
  type: proxies
  name: null
  file: pnc8LVDSL8mP.yaml
  updated: 1783789053
- uid: gm7P3SPINisf
  type: groups
  name: null
  file: gm7P3SPINisf.yaml
  updated: 1783789053
- uid: LxNsSXNAgUql
  type: local
  name: 三毛机场临时配置文件-20260606.yaml
  file: LxNsSXNAgUql.yaml
  desc: ''
  updated: 1783789054
  option:
    merge: mb8K8IRyb7jZ
    script: sY3BUB6D8d4i
    rules: rrDaWXsjQKS8
    proxies: pnc8LVDSL8mP
    groups: gm7P3SPINisf
- uid: miw57l7zJPHU
  type: merge
  name: null
  file: miw57l7zJPHU.yaml
  updated: 1783789382
- uid: sb9HwUbnAOeN
  type: script
  name: null
  file: sb9HwUbnAOeN.js
  updated: 1783789382
- uid: r0SdmkP0McMs
  type: rules
  name: null
  file: r0SdmkP0McMs.yaml
  updated: 1783789382
- uid: pt6CvpV51Gpr
  type: proxies
  name: null
  file: pt6CvpV51Gpr.yaml
  updated: 1783789382
- uid: g5KarMAGReGA
  type: groups
  name: null
  file: g5KarMAGReGA.yaml
  updated: 1783789382
- uid: RQeqWRX5X3dl
  type: remote
  name: 一千零一夜
  file: RQeqWRX5X3dl.yaml
  desc: ''
  url: https://sub-1.smjcdh.top/smjc/api/v1/client/subscribe?token=ff28e95f9702b2582b6407f1c0ec1856
  extra:
    upload: 368447
    download: 3341434
    total: 1288490188800
    expire: 1791637858
  updated: 1783789382
  option:
    update_interval: 1440
    allow_auto_update: true
    merge: miw57l7zJPHU
    script: sb9HwUbnAOeN
    rules: r0SdmkP0McMs
    proxies: pt6CvpV51Gpr
    groups: g5KarMAGReGA
